apiVersion: v1
kind: Service
metadata:
  name: lb
spec:
  selector:
    app: lb
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: lb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lb
  template:
    metadata:
      labels:
        app: lb
    spec:
      containers:
        - name: nginx
          image: nginx
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
      volumes:
        - name: nginx-config
          hostPath:
            path: ./nginx.conf

---

apiVersion: v1
kind: Service
metadata:
  name: snooze1
spec:
  selector:
    app: snooze1
  ports:
    - protocol: TCP
      port: 5201
      targetPort: 5200

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: snooze1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snooze1
  template:
    metadata:
      labels:
        app: snooze1
    spec:
      containers:
        - name: snooze
          image: snoozeweb/snooze
          env:
            - name: DATABASE_URL
              value: "mongodb://mongo1:27017,mongo2:27017,mongo3:27017/snooze?replicaSet=rs0"
            - name: SNOOZE_CLUSTER
              value: "snooze1:5200,snooze2:5200,snooze3:5200"
      ports:
        - containerPort: 5200
      dependsOn:
        - name: mongo1

---

apiVersion: v1
kind: Service
metadata:
  name: snooze2
spec:
  selector:
    app: snooze2
  ports:
    - protocol: TCP
      port: 5202
      targetPort: 5200

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: snooze2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snooze2
  template:
    metadata:
      labels:
        app: snooze2
    spec:
      containers:
        - name: snooze
          image: snoozeweb/snooze
          env:
            - name: DATABASE_URL
              value: "mongodb://mongo1:27017,mongo2:27017,mongo3:27017/snooze?replicaSet=rs0"
            - name: SNOOZE_CLUSTER
              value: "snooze1:5200,snooze2:5200,snooze3:5200"
      ports:
        - containerPort: 5200
      dependsOn:
        - name: mongo1

---

apiVersion: v1
kind: Service
metadata:
  name: snooze3
spec:
  selector:
    app: snooze3
  ports:
    - protocol: TCP
      port: 5203
      targetPort: 5200

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: snooze3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snooze3
  template:
    metadata:
      labels:
        app: snooze3
    spec:
      containers:
        - name: snooze
          image: snoozeweb/snooze
          env:
            - name: DATABASE_URL
              value: "mongodb://mongo1:27017,mongo2:27017,mongo3:27017/snooze?replicaSet=rs0"
            - name: SNOOZE_CLUSTER
              value: "snooze1:5200,snooze2:5200,snooze3:5200"
      ports:
        - containerPort: 5200
      dependsOn:
        - name: mongo1

---

apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: example-mongodb
spec:
  members: 3
  type: ReplicaSet
  version: "6.0.5"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: mongo-user
      db: admin
      passwordSecretRef:
        name: mongo-user-pw
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
      scramCredentialsSecretName: mongo-scram
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib

---

apiVersion: v1
kind: Secret
metadata:
  name: mongo-user-pw
type: Opaque
stringData:
  password: mongo_pw_123